### ISSUE TITLE
tokenLimit duplicates entries on enter key press

### ISSUE THREAD

**Issue by robzolkos** [vdepizzol/jquery-tokeninput#1]
This is a fantastic fork of the tokeninput project.   Just one thing I noticed, when limiting the tokenLimit to 1 (ie I only want to have one entry in the text box),   if I press enter in a custom value, and then press enter a few times, then every time I press enter it will add the duplicate entry.

Hopefully this is an easy fix :)

**Comment by vdepizzol** [comment]
Hey RobZolkos. Thanks for your feedback on my fork of tokeninput!
Just checked the code and fixed this little issue in the last commit (f99ffe7bd93fb9bf3e7d09ad15425f32054783bb). Thank you!

**Comment by robzolkos** [comment]
perfect thanks!  I found one more bug. I'll create another issue.
