### ISSUE TITLE
preventDuplicates doesn't allow more than one custom entry

### ISSUE THREAD

**Issue by robzolkos** [vdepizzol/jquery-tokeninput#2]
As per the title. 

I have the following setting set.
allowCustomEntry: true,
tokenLimit: 3,
theme: "facebook",
preventDuplicates: true

You cannot add more than one custom entry it seems?

**Comment by robzolkos** [comment]
This is based off the latest master btw, about 30 mins ago :)

**Comment by vdepizzol** [comment]
Hey again, Rob.
Tried with the settings above with latest master, and everything seems to be correctly working. Are you trying to use tokeninput getting local or external data?
Regards.

**Comment by robzolkos** [comment]
I'm using the demo.html provided in the repo.   So with the above settings (I just add them to the custom entry example), try adding a custom entry, example  github  and then add a TV show from the search example Dexter  and then try entering another custom entry example  javascript.    You will find that it won't work.  I'm using the ENTER key to add these by the way.

**Comment by vdepizzol** [comment]
Hey Roby. I saw the error you mentioned here on using f99ffe7bd93fb9bf3e7d09ad15425f32054783bb as last commit. However, when using master (ab52568bc0e846a11a65068782ae49f9cf80d0b9) everything worked as expect. Can you confirm?

Thank you!

**Comment by robzolkos** [comment]
I tried with latest master and still broken.

**Comment by alexgorbatchev** [comment]
@RobZolkos is that still an issue? it's working well for me. What browser are you using?

**Comment by robzolkos** [comment]
No working fine now.  I'm using Chrome.
