### ISSUE TITLE
tokenLimit 1 and prePopulate -> wrong input size

### ISSUE THREAD

**Issue by caplod** [vdepizzol/jquery-tokeninput#3]
if i have the settings 

tokenLimit: 1
and prePopulate  set

i have a doubled height  input field.

**Comment by vdepizzol** [comment]
hey caplod. can you confirm it is working right now? commited ab52568bc0e846a11a65068782ae49f9cf80d0b9

**Comment by caplod** [comment]
its working! thanks for the quick fix.
