### ISSUE TITLE
Tab not going to next focusable

### ISSUE THREAD

**Issue by ghost** [vdepizzol/jquery-tokeninput#4]
We need to press TAB twice to go to next focusable element. Any idea?

**Comment by vdepizzol** [comment]
Did you tried only on demo.html to check this behavior? There are plenty of submit buttons there which are also focused.

**Comment by wiradikusuma** [comment]
Oops, I should have been more specific. Here's my use case:

I have a form with several text fields. Naturally, people move to next field by pressing TAB.
Now, one of those fields uses tokeninput with "tokenLimit: 1". After you type in, choose some data from dropdown, then you press tab, you expect the field to be filled from your selection AND the cursor moves to next field.

But instead, it just lost focus, and you need to press TAB again. What we need to do is to go to next focusable field on 1st TAB. If it's not possible/desirable, maybe we can highlight the textfield?

**Comment by vdepizzol** [comment]
Hey wiradikusuma. I don't think we should offer different behavior for TAB press when tokenLimit exists or not. In our situation, TAB will work just like RETURN, and after trying with a custom theme that provides highlight on focus, it just worked as expected with users in my test scene.

I would say that providing highlight in the field might be enough in this case. For that, I made <code>token-input-focus</code> class a while ago, that is applied when the field is selected. What do you think?

**Comment by wiradikusuma** [comment]
Hi Vinicius, thanks for your reply. I recorded the problem in video format: http://dl.dropbox.com/u/3312526/tokeninput_not_focusing.mov
(I hope you can hear me typing the Tab key twice :P )
Anyway if you think this is non-issue, i'll close this. I'm sorry to trouble you :)
