### ISSUE TITLE
allowCustomEntry: true gives active record error

### ISSUE THREAD

**Issue by dcb-ror** [vdepizzol/jquery-tokeninput#8]
Hi I found your fork of jquery-tokeninput after watching and following ryan bates railscasts. This fork is supposed to give the ability to add new entries by using the allowCustomEntry: true method. I added the method to my application.rb file and as a result I can enter custom names and a name with an 'X' to delete is created. However, when I submit the form I am given an active record error as follows:

ActiveRecord::RecordNotFound in PostsController#create

Couldn't find Artist with ID=0

It seems to be breaking when actually trying to create the new entry, my code follows the railscasts exactly. Let me know if I can show you anything which would help. Thanks

**Comment by vdepizzol** [comment]
Hello @dcb-ror. My fork of jquery-tokeninput produces by default a different output when using custom entries (for escaping reasons).

For instance, while original jquery-tokeninput would output <code>164,573,843</code> for existing elements, my fork would output by default <code>164,573,842,'Custom Entry'</code>, with single quotes in the new elements.

You must edit your Rails application to match this behavior and add a new entry when a string is provided in single quotes.

Please try the demo.html and test the output (by pressing the submit buttons) of the demonstrations with allowCustomEntry.

Thank you.
